version: '3.9'

services:
  postgres:
      image: postgres:15.3-alpine3.18
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=db
      ports:
        - '5432:5432'
      volumes:
        - ./volumes/db:/var/lib/postgresql/data
