FROM golang:1.21-alpine as builder
WORKDIR /app
COPY . .
RUN go build -o /app/bin/known-anywhere .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/bin/known-anywhere /app/
CMD ["./known-anywhere"]
