FROM golang:1.23-alpine as builder
WORKDIR /app
COPY . .
RUN go build -o known-socially .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/known-socially /app/bin
COPY --from=builder /app/known-socially .
CMD ["./known-socially"]
